version: 0.2

phases: 
    pre_build: 
        commands:
            - echo Test code...
            - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - echo Logging in to Amazon ECR...
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com 

    build: 
        commands: 
            - echo repo name is $IMAGE_REPO_NAME
            - echo tag is $IMAGE_TAG
            - echo docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . 
            - echo docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 

    post_build: 
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image
            - echo docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
